---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  #name: letsencrypt-staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: marcin.gluc@clearobject.com
    privateKeySecretRef:
      name: letsencrypt-sec
      #name: letsencrypt-sec-staging
    http01: {}