Master:
  InstallPlugins:
    - kubernetes:1.12.6
    - workflow-job:2.24
    - workflow-aggregator:2.5
    - credentials-binding:1.16
    - git:3.9.1
    - google-oauth-plugin:0.6
    - google-source-plugin:0.3
  Cpu: "1"
  Memory: "3500Mi"
  JavaOpts: "-Xms3500m -Xmx3500m"
  #ref link: https://github.com/helm/charts/issues/3012 ; https://www.youtube.com/watch?v=eMOzF_xAm7w ; https://github.com/helm/charts/issues/2635
  ServiceType: ClusterIP
  HostName: "build.co.clearobject.com"
  Ingress:
    Annotations:
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/tls-acme: "true"
      
    TLS:
      - secretName: build.co.clearobject.com
        hosts:
          - build.co.clearobject.com
Agent:
  Enabled: true
Persistence:
  Size: 100Gi
NetworkPolicy:
  ApiVersion: networking.k8s.io/v1
rbac:
  install: true
  serviceAccountName: cd-jenkins